import { AlertCircle, ShieldCheck } from "lucide-react";
import type { AnomalyInsight } from "@/lib/types";

type InsightsPanelProps = {
  insights: AnomalyInsight[];
};

export function InsightsPanel({ insights }: InsightsPanelProps) {
  return (
    <aside className="rounded-lg border border-white/10 bg-white/[0.05] p-4">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-white">Anomaly Insights</h2>
          <p className="text-sm text-slate-400">Signals generated by the reconciliation pass.</p>
        </div>
        <AlertCircle className="text-amber-200" size={22} aria-hidden />
      </div>

      {insights.length === 0 ? (
        <div className="rounded-lg border border-emerald-300/20 bg-emerald-300/10 p-4">
          <ShieldCheck className="mb-3 text-emerald-200" size={24} aria-hidden />
          <p className="text-sm font-semibold text-emerald-100">No anomalies detected</p>
          <p className="mt-1 text-sm text-emerald-100/70">
            Current logs reconcile cleanly across source order and timestamps.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {insights.map((insight) => (
            <article key={insight.id} className="rounded-lg border border-white/10 bg-black/20 p-3">
              <div className="flex items-center justify-between gap-3">
                <h3 className="text-sm font-semibold text-slate-100">{insight.title}</h3>
                <span className="rounded-md bg-amber-300/15 px-2 py-1 text-xs font-semibold text-amber-200">
                  {insight.severity}
                </span>
              </div>
              <p className="mt-2 text-sm leading-6 text-slate-400">{insight.description}</p>
            </article>
          ))}
        </div>
      )}
    </aside>
  );
}
